[package]
name = "water"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
bevy = { version = "0.14", features = ["dynamic_linking"]}

[dependencies]
bevy = { version = "0.14", features = ["jpeg"] }
bevy_water = "0.14"
bevy_panorbit_camera = "0.19"